# Generated by Django 2.0.7 on 2018-07-23 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangobin.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangobin', '0004_auto_20180722_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='active',
        ),
        migrations.RemoveField(
            model_name='author',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_logged_in',
        ),
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='default_expiration',
            field=models.CharField(choices=[('never', 'Never'), ('1 week', '1 Week'), ('1 month', '1 Month'), ('6 months', '6 Months'), ('1 year', '1 Year')], default='never', max_length=10),
        ),
        migrations.AddField(
            model_name='author',
            name='default_exposure',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='author',
            name='default_language',
            field=models.ForeignKey(default=djangobin.models.get_default_language, on_delete=django.db.models.deletion.CASCADE, to='djangobin.Language'),
        ),
        migrations.AddField(
            model_name='author',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
